"""
api/chat.py
-----------
/api/v1/chat  — The "General Brain" (Gemini always)

  POST /api/v1/chat/  (multipart/form-data)

  Fields:
    message : str   (required)
    pdf     : file  (optional)

  Logic:
    PDF attached → Gemini answers from PDF; if not found, falls back to general knowledge.
    No PDF       → Gemini answers directly from general knowledge.

  NEVER returns "I don't have that information."
  That response is strictly reserved for /api/v1/qa.
"""

import logging
from typing import Optional

from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status

from schemas.chat import ChatResponse
from services.gemini_service import gemini_service

logger = logging.getLogger(__name__)
router = APIRouter()

_MAX_PDF_SIZE = 10 * 1024 * 1024  # 10 MB


import json
from schemas.chat import ChatResponse, ChatMessage

PAGE_CONTEXTS = {
    "Live Dashboard": (
        "You are looking at the 'Live Dashboard' page. This page displays a real-time 'Operational Pulse' line chart using Recharts. "
        "It displays live-updating telemetry readings that fluctuate every 3 seconds, generated by our background asyncio worker thread. "
        "It tracks KPIs like Solar Generation (2.0 to 5.5 kW), Grid Draw (based on active house devices), and home efficiency percentages."
    ),
    "Usage History": (
        "You are looking at the 'Usage History' page. This page shows bar charts and statistics tracking historical household energy consumption "
        "and cumulative costs. Users can toggle filters for Daily, Weekly, and Monthly views, helping them analyze solar offsets and peak load draws."
    ),
    "Smart Control": (
        "You are looking at the 'Smart Control' page, the IoT automation command center. It features card switches to toggle smart appliances "
        "(AC, EV Charger, Heater, Fridge, etc.) ON or OFF. This page is built using a 'Zero-Latency Optimistic UI' pattern: "
        "clicking a switch instantly toggles the local React state, dispatches a silent backend PATCH write, and rolls back the toggle with "
        "a warning alert if the backend server throws a network error."
    ),
    "Billing & Invoices": (
        "You are looking at the 'Billing & Invoices' page. It provides a financial budget progress bar and simulated cost projections. "
        "If projections exceed the budget limit, the layout turns red showing an 'Over Budget' alert. Users can view past invoices and click "
        "'Download' to instantly generate custom styled PDF files locally using the client-side jsPDF library."
    )
}

@router.post(
    "/",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="General AI chat — always powered by Gemini",
    description=(
        "Answers any question using the Gemini API. Supports conversation history for context memory."
    ),
    tags=["chat"],
)
async def chat_endpoint(
    message: str = Form(..., min_length=1, max_length=2000),
    history: Optional[str] = Form(None, description="JSON string of ChatMessage list"),
    current_page: Optional[str] = Form(None, description="The name of the active page"),
    pdf: Optional[UploadFile] = File(None),
) -> ChatResponse:
    """
    Always uses Gemini. PDF is optional context — never required.
    """
    logger.info("📥 [Chat] message='%s' | pdf=%s | current_page=%s", message[:80], pdf.filename if pdf else None, current_page)

    pdf_context: Optional[str] = None
    sources: list[str] = []

    # ── Extract PDF text if provided ──────────────────────────────────────────
    if pdf is not None:
        if not pdf.filename.lower().endswith(".pdf"):
            raise HTTPException(
                status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
                detail="Only PDF files are supported.",
            )
        pdf_bytes = await pdf.read()
        if len(pdf_bytes) > _MAX_PDF_SIZE:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail="PDF file exceeds the 10 MB limit.",
            )
        try:
            pdf_context = gemini_service.extract_text_from_pdf(pdf_bytes)
            if not pdf_context:
                raise ValueError("PDF appears to be empty or image-only.")
            sources = [pdf.filename]
        except ValueError as e:
            raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(e))

    # ── Parse history if provided ─────────────────────────────────────────────
    parsed_history: List[Dict[str, str]] = []
    if history:
        try:
            data = json.loads(history)
            if isinstance(data, list):
                # Only keep the last 10 messages to avoid token bloat
                parsed_history = data[-10:]
        except Exception:
            logger.warning("⚠️ Failed to parse history JSON")

    # ── Always call Gemini — with or without PDF context ─────────────────────
    try:
        page_context = PAGE_CONTEXTS.get(current_page) if current_page else None
        answer = gemini_service.chat(
            message=message,
            history=parsed_history,
            pdf_context=pdf_context,
            page_context=page_context
        )
        logger.info("📤 [Chat] Gemini answer generated. mode=%s | page_context=%s", "pdf" if pdf_context else "general", bool(page_context))
        return ChatResponse(
            answer=answer,
            sources=sources,
            mode="general",
        )
    except RuntimeError as e:
        logger.exception("❌ [Chat] Gemini error: %s", e)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(e),
        )
